branch-defaults:
  dev:
    environment: api-dev
global:
  application_name: api
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
